version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: martha4splitthoff/reverseproxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: martha4splitthoff/restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: martha4splitthoff/restapi-feed
    #version 0.1.2 
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: martha4splitthoff/frontend
